name: Cypress Tests

on: 
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.9.0'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in Chrome
        run: xvfb-run cypress run --headed --browser chrome
        env:
          TERM: xterm
          # Include Chrome's specific environment flags for CI
          CYPRESS_browser: chrome
